### ISSUE TITLE
Request for transparency support

### ISSUE THREAD

**Issue by eromatiya** [turing753/minimal-functional-fox#25]
By enabling `gfx.webrender.all` in `about:config` and adding the snippet below in your theme, I managed to add a transparency with a compositor. It would be sweet if you implement this in your theme.

```css
#TabsToolbar, #titlebar, #main-window, #navigator-toolbox {
	-moz-appearance: none !important;
	background-color: transparent !important;
	background-image: none !important;
}
```

Here's what it looks like:

![image](https://user-images.githubusercontent.com/40349590/81641977-dc281700-9454-11ea-9d3d-1cb6f37fb2a7.png)
